version: '3'

services:
  node:
    container_name: experience_node_1
    build:
      context: docker/node/
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
     - .:/usr/src/app:cached
     - node_modules:/usr/src/app/node_modules:delegated
    ports:
      - "8089:8089"
    networks:
     - experiencenet

  db:
    container_name: experience_db_1
    build:
      context: docker/mongo/
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: 123456
      MONGODB_USERNAME: experience
      MONGODB_PASSWORD: experience
      MONGODB_DATABASE: experience
    networks:
      - experiencenet

# db:
#    container_name: experience_db_1
#    build:
#      context: docker/postgres/
#      dockerfile: Dockerfile
#    ports:
#      - "5434:5432"
#    environment:
#      POSTGRES_PASSWORD: experience
#      POSTGRES_DB: experience
#      POSTGRES_USER: experience
#    volumes:
#      - data:/var/lib/postgresql/data
#    networks:
#      - experiencenet

  mail:
    container_name: experience_mail_1
    image: mailhog/mailhog:latest
    ports:
      - "8027:8025"
    networks:
      - experiencenet

  s3:
    container_name: experience_s3_1
    image: minio/minio
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 12345678
    volumes:
      - s3:/data
    networks:
      - experiencenet
    command: server /data

networks:
  experiencenet:
    driver: "bridge"

volumes:
  node_modules:
    driver: "local"
  data:
    driver: "local"
  s3:
    driver: "local"
             
