version: '3.6'

services:
  node:
    container_name: experience_node_1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: ${STAGE}
    ports:
      - "8089:8089"
      - "9229:9229"
    labels:
      - traefik.http.routers.api.rule=Host(`api.domain.com`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=lets-encrypt
      - traefik.port=80
    volumes:
      - ./dist:/home/node/app/dist
      - ./src:/home/node/app/src
      - ./config:/home/node/app/config:cached
      - ./.env:/home/node/app/.env
    networks:
     - experiencenet

  db:
    container_name: experience_db_1
    restart: always
    build:
      context: docker/mongo/
      dockerfile: Dockerfile
    ports:
      - "27018:27017"
    networks:
     - experiencenet
    environment:
      MONGODB_ROOT_PASSWORD: 123456
      MONGODB_USERNAME: experience
      MONGODB_PASSWORD: experience
      MONGODB_DATABASE: experience
    volumes:
      - data:/bitnami/mongodb

  mail:
    container_name: experience_mail_1
    restart: always
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
     - experiencenet

  redis:
    image: bitnami/redis:latest
    restart: always
    container_name: experience_redis_1
    environment:
      - REDIS_PASSWORD=ewsua132435 # Security reasons
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG # Security reasons
    ports:
      - "6379:6379"
    networks:
     - experiencenet
    volumes:
      - redis:/bitnami/redis/data

networks:
  experiencenet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
  data_sql:
    driver: "local"
  redis:
    driver: "local"
