version: '3'

services:
  db:
    container_name: experience_db_1
    restart: always
    image: digichanges/nexp:1.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=experience
      - POSTGRES_DB=experience
      - POSTGRES_PASSWORD=experience
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - experiencenet
