version: 2.1
jobs:
  test:
    working_directory: ~/circleci
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install --force
      - run: npm run ci
      - run: npm run build
      - run: npm run test-ci
      - store_artifacts:
          path: ~/circleci/coverage
          destination: reports/

  # This workflow contains a single job called "build"
  build:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ####################################
      # Run the action against code base #
      ####################################
      - name: run action
        id: run_action
        uses: fatjyc/update-submodule-action@v1.0
        with:
          user: Murzbul
          token: ${{ secrets.GH_TOKEN }}
          repo: nexp-cli
          repo_owner: DigiChanges
          committor_username: nrusso
          committor_email: natanaelrusso18@hotmail.com
          path: templates/node-experience
workflows:
  version: 2
  test_build:
    jobs:
      - test
