name: Release

on:
  push:
    branches:
      - master

  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.release.outputs.version }}

    env:
      IMAGE_NAME: digichanges/nexp-api
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    if: "!contains(github.event.head_commit.message, 'chore(release):')"
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - name: Release
        uses: ridedott/release-me-action@master
        with:
          disable-changelog: true
          node-module: true
          release-branches: '["master"]'

      - name: Output
        run: |
          echo released version: ${{ steps.release.outputs.version }}, type: ${{ steps.release.outputs.level }}
