name: Release

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: digichanges/nexp-api
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}

      - name: Release
        uses: ridedott/release-me-action@master
        with:
          disable-changelog: true
          node-module: true
          release-branches: '["master"]'

      - name: Output
        run: |
          echo released version: ${{ steps.release.outputs.version }}, type: ${{ steps.release.outputs.level }}

  build_and_push:
    needs: release
    runs-on: ubuntu-latest

    permissions:
          contents: read
          packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |-
          docker build \
            --tag "digichanges/$IMAGE_NAME:${{ needs.release.outputs.version }}" \
            --tag "digichanges/$IMAGE_NAME:latest" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Publish
        run: docker push "digichanges/$IMAGE_NAME" --all-tags
